version: "2"
services:
  web:
    image: nginx:alpine
    ports:
        - "8080:80"
    volumes:
        - ./app:/skeleton/
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    image: php:7-fpm-alpine
    volumes:
        - ./app:/skeleton/